"""rename department

Revision ID: 4a804a7cbe3d
Revises: 3fd9c6c4c0c0
Create Date: 2024-01-09 19:27:02.693104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a804a7cbe3d"
down_revision = "3fd9c6c4c0c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
