"""rename address

Revision ID: d40da758b1e0
Revises: 4a804a7cbe3d
Create Date: 2024-01-09 19:32:05.640552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d40da758b1e0"
down_revision = "4a804a7cbe3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    # op.drop_column('departments', 'address')
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    # op.drop_column('departments', 'location')
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
